nginx:
  image: nginx:stable-alpine
  container_name: laravel_nginx
  ports:
    - "8080:80"
  volumes:
    - .:/var/www
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  depends_on:
    - app
  networks:
    - laravel
